apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
  name: {{ template "brigade-eventgrid-gateway.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /cloudevents
        backend:
          serviceName: {{ template "brigade-eventgrid-gateway.name" . }}
          servicePort: {{ .Values.service.externalPort }}
      - path: /simpleevents
        backend:
          serviceName: brigade-brigade-generic-gateway
          servicePort: {{ .Values.service.externalPort }}          